### ISSUE TITLE
[FEATURE] Header

### ISSUE THREAD

**Issue by YuriDevAT** [YurisCodingClub/pro-check#2]
### Description

Create a Header with any logo as a placeholder until #1  is finished. (Will be another issue).

### Acceptance Criteria (AC)

- [ ] Create a component called `Header.js` and save it in a folder called components in the `src` directory
- [ ] A header is shown with a logo and the name in it
- [ ] The header is imported and displayed in the `App.js` component
- [ ] Only the header is displayed
- [ ] Plain HTML, no styling added
- [ ] The header meets accessibility standards like semantic HTML
- [ ] The header is fixed (stays at its position even when scrolling)

**Comment by Giriraj-Roy** [comment]
Hello ma'am,
I have gone through the repository and the given instructions. The issue seems to attract my interest and excites me to work on it. I humbly wait for you to assign the task to me if your analysis of my profile allows.

Yours Sincerely,
Giriraj Roy.

**Comment by YuriDevAT** [comment]
Since you have not answered by now, I will unassign you and leave this issue to someone else.

**Comment by MusfiqDehan** [comment]
Hi @YuriDevAT ,
I would love to work on this issue. Can you assign me?

**Comment by YuriDevAT** [comment]
Sure, @MusfiqDehan, go ahead 🙂
