### ISSUE TITLE
[FEATURE] Form Code and Live View

### ISSUE THREAD

**Issue by YuriDevAT** [YurisCodingClub/pro-check#4]
### Description

As a User, I want to see a checklist where I can check items to showcase my progress.

### Acceptance Criteria (AC) for beginners

- [ ] Create a component called `Code.js` and save it in a folder called components in the `src` directory
- [ ] Heading: Code and Live View
- [ ] Inputfields must be editable
- [ ] Input fields are [accessible](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/form)
- [ ] No stylings but plain html
- [ ] The new component is imported and displayed in the `App.js` component
- [ ] Only the new component is displayed

### Additional AC if you are more experienced

- [ ] Save data in localStorage

### Screenshots

<img width="914" alt="Checklist for code and live view" src="https://user-images.githubusercontent.com/54622834/192697527-63fc0798-5786-4e17-ae3d-71a08e200079.png">

Find the text [here in the job-seeker wiki.](https://github.com/YuriDevAT/job-seekers/wiki/Checklist-for-your-portfolio-projects)

### Additional information

Please do not hesitate to ask me about accessible forms in case you are unsure.
Accessibility and your inexperience with this topic should not be the reason you are not work on this issue, but to learn about it.

**Comment by error707-persona** [comment]
Hello, can you assign this to me? i want to work on it

**Comment by Charvine-300** [comment]
Hello, @YuriDevAT I am a student from Frontend Foxes and spotted your message in the #hacktoberfest channel. I would like to be assigned this issue to contribute to. Looking forward to your reply 😊

**Comment by YuriDevAT** [comment]
Nice, welcome @Charvine-300 👍🏽

**Comment by Charvine-300** [comment]
Hey, @YuriDevAT I would like more information on the criteria which states, "Inputfields must be editable". Do you mean that the user should be able to change the content of any item in the checklist when they click it or should there be an input bar that allows users to insert new tasks?

Thank you

**Comment by YuriDevAT** [comment]
Hey  @Charvine-300, sure. I am sorry if my description was not clear enough. It means that when the user clicks on the checkbox, it should change its value to checked/unchecked, depending on the current state.

If you have any other question, feel free to reach out to me any time.

**Comment by Charvine-300** [comment]
Ok then. So, it's about ticking off the items on the list instead of changing the actual content of the list item?? 
Understood 👍🏾

In one of your README files, you stated that the merge reviews are on Saturday, yeah?
I'll have it ready before then ✨

**Comment by YuriDevAT** [comment]
No worries, Saturday is just a day where I can make sure the PR can be reviewed during Hacktoberfest. Most likely, I will find time on other days as well.

**Comment by Charvine-300** [comment]
Ok then. Understood

**Comment by Charvine-300** [comment]
Hey, @YuriDevAT I have completed my issue and requested a pull to the main branch. Check it out 😊✨
